CREATE TABLE BANK_ACCOUNT (USER_DNI VARCHAR(255), USD DOUBLE, ORDERS_EXECUTED BIGINT);
CREATE TABLE ORDERS (
    ID BIGINT PRIMARY KEY,
    SELLER_DNI VARCHAR(255),
    BUYER_DNI VARCHAR(255),
    USD_AMOUNT DOUBLE,
    BUYER_COMMISSION DOUBLE,
    JAVA_COIN_PRICE DOUBLE,
    ORDER_STATE VARCHAR(255)
);
