CREATE TABLE BANK_ACCOUNT (USER_DNI VARCHAR(255), USD BIGINT, ORDERS_EXECUTED BIGINT);
CREATE TABLE ORDERS (
    ID BIGINT PRIMARY KEY,
    SELLER_DNI VARCHAR(255),
    BUYER_DNI VARCHAR(255),
    USD_AMOUNT BIGINT,
    JAVA_COIN_PRICE BIGINT,
    ORDER_STATE VARCHAR(255)
);
